[tool.poetry]
name = "pilecrystal"
version = "0.1.0"
description = ""
authors = ["= <=>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pymatgen = "^2024.1.27"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
